import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE
} from '@/constants/navigation.constant'


import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    /** Example purpose only, please remove */
    {
        key: 'usuarios',
        path: '/usuarios',
        title: 'Usuarios',
        translateKey: 'nav.singleMenuItem',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'projects',
        path: '/proyectos',
        title: 'Proyectos',
        translateKey: 'nav.projects',
        icon: 'projectsIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'singleMenuItem3',
        path: '/single-menu-view',
        title: 'Planificador',
        translateKey: 'nav.singleMenuItem3',
        icon: 'plannerIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'singleMenuItem4',
        path: '/single-menu-view',
        title: 'Chat',
        translateKey: 'nav.singleMenuItem4',
        icon: 'chatIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'singleMenuItem5',
        path: '/recursos',
        title: 'Recursos',
        translateKey: 'nav.singleMenuItem5',
        icon: 'resouceIcon',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'separator6',
        path: '',
        title: '________________',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [],
    },
    {
        key: 'singleMenuItem6',
        path: '/single-menu-view',
        title: 'Mercados',
        translateKey: 'nav.singleMenuItem6',
        icon: 'projectsMarket',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'singleMenuItem7',
        path: '/agricultores',
        title: 'Agricultores',
        translateKey: 'nav.singleMenuItem7',
        icon: 'projectsAgri',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'singleMenuItem8',
        path: '/single-menu-view',
        title: 'Certificación',
        translateKey: 'nav.singleMenuItem8',
        icon: 'projectsCheck',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'separator9',
        path: '',
        title: '________________',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [],
    },
    {
        key: 'singleMenuItem9',
        path: '/single-menu-view',
        title: 'Configuración',
        translateKey: 'nav.singleMenuItem9',
        icon: 'projectsSetting',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'singleMenuItem10',
        path: '/single-menu-view',
        title: 'Soporte',
        translateKey: 'nav.singleMenuItem10',
        icon: 'projectsSupport',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
]

export default navigationConfig
