export const users = [
    {
      profileImage: "public/img/rurawa-logo/user1.png",
      name: "James Ortigoza",
      email: "james.ortigoza@example.com",
      group: "Admins",
      zone: "Santander, Bucaramanga",
      contact: "329 999 9999",
      profession: "Software Engineer",
      isActive: true,
    },
    {
      profileImage: "public/img/rurawa-logo/user2.png",
      name: "Ana Martínez",
      email: "ana.martinez@example.com",
      group: "Editors",
      zone: "Antioquia, Medellín",
      contact: "301 555 1234",
      profession: "Content Manager",
      isActive: false,
    },
    {
      profileImage: "public/img/rurawa-logo/user3.png",
      name: "Carlos Gómez",
      email: "carlos.gomez@example.com",
      group: "Viewers",
      zone: "Cundinamarca, Bogotá",
      contact: "315 888 5678",
      profession: "Graphic Designer",
      isActive: true,
    },
    {
      profileImage: "public/img/rurawa-logo/user4.png",
      name: "Lucía Fernández",
      email: "lucia.fernandez@example.com",
      group: "Admins",
      zone: "Valle del Cauca, Cali",
      contact: "320 123 4567",
      profession: "Project Manager",
      isActive: true,
    },
    {
      profileImage: "public/img/rurawa-logo/user5.png",
      name: "Pedro Torres",
      email: "pedro.torres@example.com",
      group: "Editors",
      zone: "Boyacá, Tunja",
      contact: "300 444 7777",
      profession: "Backend Developer",
      isActive: false,
    },
    {
      profileImage: "public/img/rurawa-logo/user6.png",
      name: "Laura Castro",
      email: "laura.castro@example.com",
      group: "Viewers",
      zone: "Risaralda, Pereira",
      contact: "302 789 6543",
      profession: "UI/UX Designer",
      isActive: true,
    },
    {
      profileImage: "public/img/rurawa-logo/user7.png",
      name: "Miguel Rojas",
      email: "miguel.rojas@example.com",
      group: "Admins",
      zone: "Nariño, Pasto",
      contact: "305 111 2222",
      profession: "DevOps Engineer",
      isActive: true,
    },
    {
      profileImage: "public/img/rurawa-logo/user8.png",
      name: "Sara López",
      email: "sara.lopez@example.com",
      group: "Editors",
      zone: "Atlántico, Barranquilla",
      contact: "311 333 4444",
      profession: "Marketing Specialist",
      isActive: false,
    },
    {
      profileImage: "public/img/rurawa-logo/user9.png",
      name: "Andrés Mejía",
      email: "andres.mejia@example.com",
      group: "Viewers",
      zone: "Huila, Neiva",
      contact: "316 555 6666",
      profession: "Data Analyst",
      isActive: true,
    },
    {
      profileImage: "public/img/rurawa-logo/user10.png",
      name: "Daniela Rodríguez",
      email: "daniela.rodriguez@example.com",
      group: "Admins",
      zone: "Caldas, Manizales",
      contact: "317 777 8888",
      profession: "System Architect",
      isActive: true,
    },
    {
      profileImage: "public/img/rurawa-logo/user11.png",
      name: "Juan Pérez",
      email: "juan.perez@example.com",
      group: "Viewers",
      zone: "Córdoba, Montería",
      contact: "318 999 0000",
      profession: "IT Support",
      isActive: false,
    },
    {
      profileImage: "public/img/rurawa-logo/user12.png",
      name: "Natalia Sánchez",
      email: "natalia.sanchez@example.com",
      group: "Editors",
      zone: "Magdalena, Santa Marta",
      contact: "319 101 2020",
      profession: "SEO Expert",
      isActive: true,
    },
    {
      profileImage: "public/img/rurawa-logo/user13.png",
      name: "Ricardo Vargas",
      email: "ricardo.vargas@example.com",
      group: "Admins",
      zone: "Cesar, Valledupar",
      contact: "322 303 4040",
      profession: "Security Engineer",
      isActive: true,
    },
    {
      profileImage: "public/img/rurawa-logo/user14.png",
      name: "Mónica Herrera",
      email: "monica.herrera@example.com",
      group: "Editors",
      zone: "Tolima, Ibagué",
      contact: "323 505 6060",
      profession: "Product Manager",
      isActive: false,
    },
    {
      profileImage: "public/img/rurawa-logo/user15.png",
      name: "Oscar Ramírez",
      email: "oscar.ramirez@example.com",
      group: "Viewers",
      zone: "Norte de Santander, Cúcuta",
      contact: "324 707 8080",
      profession: "Network Engineer",
      isActive: true,
    },
    {
      profileImage: "public/img/rurawa-logo/user16.png",
      name: "Diana Gómez",
      email: "diana.gomez@example.com",
      group: "Admins",
      zone: "Quindío, Armenia",
      contact: "325 909 1010",
      profession: "Database Administrator",
      isActive: true,
    },
    {
      profileImage: "public/img/rurawa-logo/user17.png",
      name: "Felipe Moreno",
      email: "felipe.moreno@example.com",
      group: "Viewers",
      zone: "Caquetá, Florencia",
      contact: "326 111 2121",
      profession: "Cloud Specialist",
      isActive: false,
    },
    {
      profileImage: "public/img/rurawa-logo/user18.png",
      name: "Andrea Velasco",
      email: "andrea.velasco@example.com",
      group: "Editors",
      zone: "Guaviare, San José del Guaviare",
      contact: "327 313 4141",
      profession: "Scrum Master",
      isActive: true,
    },
    {
      profileImage: "public/img/rurawa-logo/user19.png",
      name: "Jorge Ortega",
      email: "jorge.ortega@example.com",
      group: "Admins",
      zone: "Putumayo, Mocoa",
      contact: "328 515 6161",
      profession: "Software Tester",
      isActive: true,
    },
    {
      profileImage: "public/img/rurawa-logo/user20.png",
      name: "Carolina Suárez",
      email: "carolina.suarez@example.com",
      group: "Viewers",
      zone: "Amazonas, Leticia",
      contact: "329 717 8181",
      profession: "AI Engineer",
      isActive: true,
    },
  ]